const cityData = [
    {
        id: "istanbul",
        name: "İstanbul",
        lat: 41.0082,
        lng: 28.9784,
        carbonFootprint: "Kritik (45M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["solar", "wind", "biomass"],
        description: "Türkiye'nin en yüksek enerji tüketimine sahip şehri. Sanayi ve konut yoğunluğu nedeniyle karbon salınımı kritik seviyede. Çatılarda Güneş Enerjisi (GES) ve açık denizde Rüzgar Enerjisi (RES) potansiyeli çok yüksek.",
        investmentCost: "₺12.5 Milyar",
        roi: "4.5 Yıl"
    },
    {
        id: "ankara",
        name: "Ankara",
        lat: 39.9334,
        lng: 32.8597,
        carbonFootprint: "Yüksek (20M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["solar", "biomass"],
        description: "Geniş ve düz arazileri sayesinde dev ölçekli Güneş Enerjisi Santralleri (GES) kurmak için oldukça elverişli. Aynı zamanda çevre ilçelerdeki tarımsal faaliyetler biyokütle enerjisine zemin hazırlamaktadır.",
        investmentCost: "₺8.2 Milyar",
        roi: "5.2 Yıl"
    },
    {
        id: "izmir",
        name: "İzmir",
        lat: 38.4192,
        lng: 27.1287,
        carbonFootprint: "Orta (15M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["wind", "geothermal", "solar"],
        description: "Ege'nin incisi İzmir, Türkiye'nin en güçlü rüzgar koridorlarına ve en zengin jeotermal kaynaklarına sahip. Çeşme, Karaburun ve Seferihisar yenilenebilir enerjinin merkezleri konumunda.",
        investmentCost: "₺9.0 Milyar",
        roi: "3.8 Yıl"
    },
    {
        id: "bursa",
        name: "Bursa",
        lat: 40.1824,
        lng: 29.0671,
        carbonFootprint: "Yüksek (18M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["wind", "solar", "biomass"],
        description: "Ağır sanayi ve otomotiv sektörünün kalbi. Yüksek karbon salınımını dengelemek için sanayi çatılarına GES ve Uludağ yamaçlarında RES yatırımlarına acil ihtiyaç duyulmaktadır.",
        investmentCost: "₺10.4 Milyar",
        roi: "4.1 Yıl"
    },
    {
        id: "antalya",
        name: "Antalya",
        lat: 36.8969,
        lng: 30.7133,
        carbonFootprint: "Orta (10M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["solar"],
        description: "Yılın büyük bir bölümünü güneşli geçiren Antalya, turizm tesislerinin enerji ihtiyacını karşılamak üzere çatı ve arazi tipi güneş enerjisi sistemleri için harika bir potansiyel sunar.",
        investmentCost: "₺6.5 Milyar",
        roi: "4.0 Yıl"
    },
    {
        id: "konya",
        name: "Konya",
        lat: 37.8746,
        lng: 32.4931,
        carbonFootprint: "Orta (12M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["solar", "biomass"],
        description: "Türkiye'nin en yüksek güneşlenme süresine sahip ili olan Konya'da Karapınar GES gibi mega projeler artırılabilir. Tarımsal atıklar için büyük biyogaz tesisleri kurulabilir.",
        investmentCost: "₺15.0 Milyar",
        roi: "4.8 Yıl"
    },
    {
        id: "adana",
        name: "Adana",
        lat: 37.0000,
        lng: 35.3213,
        carbonFootprint: "Orta-Yüksek (14M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["solar", "biomass", "hydro"],
        description: "Çukurova'nın tarımsal potansiyeli biyokütle için benzersiz bir hammadde sunar. Ayrıca Seyhan ve Ceyhan nehirleri üzerinde hidroelektrik ve güneş hibrit santralleri kurulabilir.",
        investmentCost: "₺7.6 Milyar",
        roi: "4.4 Yıl"
    },
    {
        id: "gaziantep",
        name: "Gaziantep",
        lat: 37.0662,
        lng: 37.3833,
        carbonFootprint: "Orta (11M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["solar", "biomass"],
        description: "Güneydoğu Anadolu'nun sanayi üssü olan Gaziantep, yüksek güneşlenme süresiyle GES yatırımlarına ve fıstık/zeytin atıklarından biyoenerji üretimine oldukça elverişlidir.",
        investmentCost: "₺6.2 Milyar",
        roi: "4.3 Yıl"
    },
    {
        id: "diyarbakir",
        name: "Diyarbakır",
        lat: 37.9144,
        lng: 40.2306,
        carbonFootprint: "Düşük (6M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["solar", "hydro"],
        description: "Güneş radyasyon oranlarının çok yüksek olduğu bir bölgedir. Geniş araziler üzerinde GES ve Dicle nehri havzasında çevreci HES projeleri ile yeşil enerji ihraç eden bir şehir olabilir.",
        investmentCost: "₺5.1 Milyar",
        roi: "3.9 Yıl"
    },
    {
        id: "erzurum",
        name: "Erzurum",
        lat: 39.9043,
        lng: 41.2679,
        carbonFootprint: "Düşük (4M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["wind", "solar"],
        description: "Soğuk iklimine rağmen yüksek rakımı sayesinde güneşlenme ve rüzgar şiddeti çok verimlidir. Karlı yüzeylerin yansıtma (albedo) etkisiyle çift yüzlü (bifacial) GES panelleri ekstra verim sağlar.",
        investmentCost: "₺4.5 Milyar",
        roi: "5.5 Yıl"
    },
    {
        id: "trabzon",
        name: "Trabzon",
        lat: 41.0027,
        lng: 39.7168,
        carbonFootprint: "Düşük (4M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["hydro", "tidal"],
        description: "Bol yağış alan engebeli arazi yapısı, mikro hidroelektrik (HES) santralleri için uygundur. Karadeniz'in hırçın dalgaları ise dalga enerjisi AR-GE faaliyetleri için biçilmiş kaftandır.",
        investmentCost: "₺3.2 Milyar",
        roi: "6.5 Yıl"
    },
    {
        id: "samsun",
        name: "Samsun",
        lat: 41.2867,
        lng: 36.3300,
        carbonFootprint: "Orta (8M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["wind", "biomass"],
        description: "Karadeniz kıyı şeridinde güçlü rüzgar alanlarına sahiptir. Çarşamba ve Bafra ovalarındaki tarımsal faaliyetler de büyük ölçekli biyogaz ve biyokütle tesislerini besleyebilir.",
        investmentCost: "₺5.8 Milyar",
        roi: "5.0 Yıl"
    },
    {
        id: "canakkale",
        name: "Çanakkale",
        lat: 40.1467,
        lng: 26.4086,
        carbonFootprint: "Düşük (6M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["wind", "tidal", "geothermal"],
        description: "Boğazın oluşturduğu hava akımları sayesinde Türkiye'nin en verimli rüzgar enerjisi potansiyeline sahiptir. Ayrıca boğaz akıntıları gelgit/akıntı enerjisi için yenilikçi bir AR-GE alanıdır.",
        investmentCost: "₺7.8 Milyar",
        roi: "3.5 Yıl"
    },
    {
        id: "denizli",
        name: "Denizli",
        lat: 37.7765,
        lng: 29.0864,
        carbonFootprint: "Düşük (5M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["geothermal", "solar"],
        description: "Türkiye'nin jeotermal başkenti konumundadır. Mevcut santrallerin yanı sıra yeni rezerv alanları keşfedilebilir. Tekstil sanayisinin enerji ihtiyacı bu şekilde yeşil enerjiyle karşılanabilir.",
        investmentCost: "₺5.4 Milyar",
        roi: "4.2 Yıl"
    },
    {
        id: "mugla",
        name: "Muğla",
        lat: 37.2153,
        lng: 28.3636,
        carbonFootprint: "Orta (7M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["solar", "wind"],
        description: "Uzun sahil şeridi rüzgar enerjisine, yıl boyu açık havası ise güneşe çok uygundur. Fosil yakıtlı mevcut santrallerin kapatılıp tamamen yeşil turizm ve enerji modeline geçilmesi planlanmaktadır.",
        investmentCost: "₺8.1 Milyar",
        roi: "4.6 Yıl"
    },
    {
        id: "mersin",
        name: "Mersin",
        lat: 36.8121,
        lng: 34.6415,
        carbonFootprint: "Orta-Yüksek (13M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["solar", "wind", "biomass"],
        description: "Akdeniz'in önemli liman ve sanayi şehri. Güneşli gün sayısının fazlalığı ve kıyı şeridinin rüzgar potansiyeli temiz enerji dönüşümü için büyük fırsat sunuyor.",
        investmentCost: "₺8.5 Milyar",
        roi: "4.2 Yıl"
    },
    {
        id: "kayseri",
        name: "Kayseri",
        lat: 38.7205,
        lng: 35.4826,
        carbonFootprint: "Orta (9M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["solar", "biomass", "wind"],
        description: "Erciyes'in eteklerinde konumlanan şehir, sanayi bölgelerinin çatılarına GES kurmak için çok avantajlı. Aynı zamanda yüksek kesimlerde verimli rüzgar koridorları mevcuttur.",
        investmentCost: "₺6.0 Milyar",
        roi: "4.7 Yıl"
    },
    {
        id: "eskisehir",
        name: "Eskişehir",
        lat: 39.7767,
        lng: 30.5206,
        carbonFootprint: "Orta (8M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["wind", "solar"],
        description: "Karasal iklim ve düzlük alanları rüzgar türbinleri için idealdir. Organize sanayi bölgelerindeki fabrikaların karbon ayak izini azaltmak için RES ve GES hibrit projeleri geliştirilebilir.",
        investmentCost: "₺5.5 Milyar",
        roi: "4.5 Yıl"
    },
    {
        id: "sanliurfa",
        name: "Şanlıurfa",
        lat: 37.1674,
        lng: 38.7939,
        carbonFootprint: "Düşük (5M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["solar", "biomass"],
        description: "GAP bölgesinin kalbi olan Şanlıurfa, devasa tarım arazileri ile biyokütle, kavurucu güneşi ile büyük ölçekli GES tarlaları kurmak için Türkiye'nin en şanslı şehirlerinden biridir.",
        investmentCost: "₺9.2 Milyar",
        roi: "3.5 Yıl"
    },
    {
        id: "balikesir",
        name: "Balıkesir",
        lat: 39.6484,
        lng: 27.8826,
        carbonFootprint: "Orta (7M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["wind", "biomass"],
        description: "Marmara ve Ege arasında köprü görevi gören Balıkesir, Türkiye'nin RES kapasitesi en yüksek illerinden. Geniş orman ve tarım arazileri de biyokütle için zengin hammadde sağlar.",
        investmentCost: "₺7.0 Milyar",
        roi: "3.8 Yıl"
    },
    {
        id: "manisa",
        name: "Manisa",
        lat: 38.6191,
        lng: 27.4289,
        carbonFootprint: "Orta-Yüksek (11M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["geothermal", "solar", "wind"],
        description: "Gelişmiş sanayisinin enerji ihtiyacını zengin jeotermal yatakları ve rüzgar enerjisi potansiyeliyle karşılama imkanına sahip önemli bir endüstri merkezidir.",
        investmentCost: "₺8.8 Milyar",
        roi: "4.0 Yıl"
    },
    {
        id: "hatay",
        name: "Hatay",
        lat: 36.2066,
        lng: 36.1572,
        carbonFootprint: "Yüksek (16M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["wind", "solar"],
        description: "Ağır demir-çelik sanayisi nedeniyle karbon salınımı oldukça yüksektir. Nur Dağları (Amanoslar) üzerindeki rüzgar akımları bu emisyonu dengeleyecek ciddi bir RES potansiyeli barındırır.",
        investmentCost: "₺9.5 Milyar",
        roi: "3.9 Yıl"
    },
    {
        id: "kahramanmaras",
        name: "Kahramanmaraş",
        lat: 37.5753,
        lng: 36.9228,
        carbonFootprint: "Orta (9M Ton/Yıl)",
        carbonLevel: "medium",
        potential: ["hydro", "solar"],
        description: "Su kaynakları ve barajlarıyla hidroelektrik enerjisi açısından zengin bir altyapıya sahiptir. Sanayi tesisleri de kendi enerjilerini üretmek için GES yatırımlarına odaklanmaktadır.",
        investmentCost: "₺6.8 Milyar",
        roi: "5.1 Yıl"
    },
    {
        id: "aydin",
        name: "Aydın",
        lat: 37.8380,
        lng: 27.8456,
        carbonFootprint: "Düşük (4M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["geothermal", "wind", "solar"],
        description: "Menderes havzasındaki sıcak su kaynakları jeotermal enerji üretimi için çok değerlidir. İklim avantajıyla tarım, turizm ve yenilenebilir enerjinin buluştuğu ideal bir şehirdir.",
        investmentCost: "₺5.9 Milyar",
        roi: "4.1 Yıl"
    },
    {
        id: "tekirdag",
        name: "Tekirdağ",
        lat: 40.9780,
        lng: 27.5117,
        carbonFootprint: "Yüksek (14M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["wind", "biomass"],
        description: "Marmara'nın sanayi yükünü çeken illerden. Fabrika yoğunluğu nedeniyle yüksek olan emisyon değerleri, Trakya rüzgarları ve tarımsal atık enerjisi (biyokütle) ile düşürülebilir.",
        investmentCost: "₺8.4 Milyar",
        roi: "4.3 Yıl"
    },
    {
        id: "sakarya",
        name: "Sakarya",
        lat: 40.7731,
        lng: 29.9398,
        carbonFootprint: "Orta-Yüksek (10M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["biomass", "hydro"],
        description: "Otomotiv ve makine sanayisiyle öne çıkar. Sakarya Nehri çevresindeki hidroelektrik potansiyeli ve orman/tarım alanlarının biyokütle kapasitesi şehri yeşil enerjiye hazırlamaktadır.",
        investmentCost: "₺6.3 Milyar",
        roi: "4.6 Yıl"
    },
    {
        id: "kocaeli",
        name: "Kocaeli",
        lat: 40.7654,
        lng: 29.9408,
        carbonFootprint: "Kritik (35M Ton/Yıl)",
        carbonLevel: "high",
        potential: ["wind", "solar"],
        description: "Türkiye'nin sanayi başkenti. Petrokimya, otomotiv ve ağır sanayi yüzünden emisyon çok kritik boyutta. Yenilenebilir enerji yatırımlarının en acil ve agresif şekilde uygulanması gereken şehir.",
        investmentCost: "₺18.0 Milyar",
        roi: "3.4 Yıl"
    },
    {
        id: "sivas",
        name: "Sivas",
        lat: 39.7477,
        lng: 37.0179,
        carbonFootprint: "Düşük (3M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["solar", "wind"],
        description: "Geniş yüzölçümü ve yüksek rakımı, özellikle açık arazi Güneş Enerjisi Santralleri (GES) için muazzam bir alan sunar. Karlı kış aylarında yansıtma avantajı sağlar.",
        investmentCost: "₺4.8 Milyar",
        roi: "5.2 Yıl"
    },
    {
        id: "malatya",
        name: "Malatya",
        lat: 38.3552,
        lng: 38.3095,
        carbonFootprint: "Düşük (4M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["solar", "hydro"],
        description: "Doğu Anadolu'nun parlayan yıldızı. Güneşlenme süresi yüksek ve barajları sayesinde hidroelektrik üretim kapasitesi stabil. Çevreci yatırımlarla sıfır karbon hedefi yakalanabilir.",
        investmentCost: "₺4.1 Milyar",
        roi: "4.9 Yıl"
    },
    {
        id: "mardin",
        name: "Mardin",
        lat: 37.3102,
        lng: 40.7360,
        carbonFootprint: "Düşük (2M Ton/Yıl)",
        carbonLevel: "low",
        potential: ["solar", "wind"],
        description: "Mezopotamya ovasına hakim rüzgarlı tepeleri ve çok yüksek güneş alma kapasitesi ile, tarihi dokusunu korurken modern yeşil enerji projeleriyle cazibe merkezi olabilir.",
        investmentCost: "₺5.0 Milyar",
        roi: "4.4 Yıl"
    }
];

// Energy type definitions for UI
const energyTypes = {
    solar: { name: "Güneş (GES)", icon: "fa-solid fa-solar-panel", color: "text-glow-yellow", bgClass: "solar" },
    wind: { name: "Rüzgar (RES)", icon: "fa-solid fa-wind", color: "text-glow-blue", bgClass: "wind" },
    hydro: { name: "Hidro (HES)", icon: "fa-solid fa-water", color: "text-glow-blue", bgClass: "hydro" },
    geothermal: { name: "Jeotermal (JES)", icon: "fa-solid fa-fire-flame-simple", color: "text-glow-red", bgClass: "geothermal" },
    biomass: { name: "Biyokütle", icon: "fa-solid fa-leaf", color: "text-glow-green", bgClass: "biomass" },
    tidal: { name: "Akıntı/Dalga", icon: "fa-solid fa-water", color: "text-glow-blue", bgClass: "tidal" }
};
